spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: xqr
    password: x15282097256@
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.xqr.admin.*
      filters: stat.,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true



