spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: xqr
    password: x15282097256@
    driver-class-name: com.mysql.jdbc.Driver
    #drui配置
    druid:
      aop-patterns: com.xqr.admin.*
      filters: stat,wall,slf4j

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      #web监控
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #单独配置
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
  redis:
    host: 1.117.217.16
    port: 6379
    password: x744713157
    client-type: jedis
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true
  application:
    name: boot-web-admin
#配置规则
#可以不写全局；配置文件，所有全局配置文件的配置都放在configuration配置项中即可
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#监控配置
management:
  endpoints:
    enabled-by-default: true #默认开启所监控断点
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
info:
  appName: boot-admin
  version: 1.1
  mavenProjectName: @project.artifactId@