spring:
  mvc:
    #开启rest风格
    hiddenmethod:
      filter:
        enabled: true
#  mvc:
    #静态资源前缀
#    static-path-pattern: /res/**
#  resources:
    #设置静态资源路径
#    static-locations: classpath:/haha/